### ISSUE TITLE
unexpected '[' in tpl_header.php on line 119

### ISSUE THREAD

**Issue by kiloforce** [gerardnico/dokuwiki-template-bootie#2]
Installed latest edition on Doku's website (https://www.dokuwiki.org/template:bootie) (Last updated on 2016-07-15) and it is throwing an error:

> PHP Parse error:  syntax error, unexpected '[' in /www/doku/lib/tpl/dokuwiki-template-bootie-master/tpl_header.php on line 119

**Comment by gerardnico** [comment]
Wouahou sorry. I just see just your ticket. It seems as a PHP version problem. Actually, it would work with PHP 5.6

**Comment by gerardnico** [comment]
I have just released a new version based on Bootstrap. Nothing really exiting. My website runs on php 7.2.5 and I don't have this issue.

Feel free to reopen if it's still present for you.
